title: Project FrankenServer
description: Proxmox + pfSense homelab with VLANs, Pi-hole, Home Assistant (sanitized docs & configs).
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
search_enabled: true
color_scheme: dark
aux_links:
  ""View on GitHub"": https://github.com/Redleg101/Project-FrankenServer
url: https://redleg101.github.io
baseurl: /Project-FrankenServer
